"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    'corsheaders',
    'django_filters',
    'rest_framework',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    'apps.accounts',
    'apps.profiles',
    'apps.sellers',
    'apps.shop',
    'apps.common',
    'apps.reviews',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('SQL_DATABASE', 'marketplace_db'),
        'USER': os.getenv('SQL_USER', 'postgres'),
        'PASSWORD': os.getenv('SQL_PASSWORD', 'postgres'),
        'HOST': os.getenv('SQL_HOST', 'db'),  # 'db' - имя сервиса в docker-compose
        'PORT': os.getenv('SQL_PORT', 5432),
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'web/static')

# MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'web/media')
MEDIA_URL = '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'accounts.User'


REST_FRAMEWORK = {
    # 'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.AcceptHeaderVersioning',
    # 'ALLOWED_VERSIONS': ['1.0', '2.0'],
    # 'DEFAULT_VERSION': '1.0',
    # 'DEFAULT_VERSIONING_CLASS': 'apps.accounts.versions.HeaderVersioning',
    'DEFAULT_VERSIONING_CLASS': 'apps.accounts.versions.QueryParameterVersioning',

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '50/minute',  # ограничения для анонимных пользователей
        'user': '100/minute',  # ограничения для авторизованных пользователей
        'my_scope': '100/minute'
    }

    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 2
}

SPECTACULAR_SETTINGS = {
    "TITLE": "My First API",  # название проекта
    "VERSION": "1.0",  # версия проекта
    "SERVE_INCLUDE_SCHEMA": False,  # исключить эндпоинт /schema
    "SWAGGER_UI_SETTINGS": {
        "persistAuthorization": True,  # не сбрасывать авторизацию
    },
}


SIMPLE_JWT = {
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
}


CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",            # Соответствует localhost с любым портом
]

"""
{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDUyNjc4OCwiaWF0IjoxNzY3OTM0Nzg4LCJqdGkiOiI2ZDMxMjc1YmZkYjA0ZjU3OTE0MjYzZjYwMWQzYzdjZiIsInVzZXJfaWQiOiJjYTc3YzU0Yy0yMzQ5LTRjMTAtODhmYy0zZTBiMThlZmNjZGIiLCJncm91cCI6ImFkbWluIn0._d8QtxTb4fqdnNHXlY78oLBWyVpkn8BRlVvOl9efjBU",
  "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NTM5NTg4LCJpYXQiOjE3Njc5MzQ3ODgsImp0aSI6IjE1MjY4NDVmOTkwOTRhNzBiNGM5MTE4NDVhZDk0MWMzIiwidXNlcl9pZCI6ImNhNzdjNTRjLTIzNDktNGMxMC04OGZjLTNlMGIxOGVmY2NkYiIsImdyb3VwIjoiYWRtaW4ifQ.aPwvFCXT9k3I_dMi5BJUinlNBQGCYop2sbN1lk84gJQ"
}


{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3MDUyNjg2NiwiaWF0IjoxNzY3OTM0ODY2LCJqdGkiOiJhNmI3MmQ2YWM0ZGM0NmYwYmNlNmYzMDY5ZDYzZTcwYyIsInVzZXJfaWQiOiJiZWU2MWZjMS0yOWY0LTRjMzgtOGU2Zi0yOGE3YmQxNzUwZDIiLCJncm91cCI6InVzZXIiLCJyb2xlIjoiQlVZRVIifQ.CdHgYMjOwFEb72GLnrVBlDRWklh77fin8vwRdSQWtRU",
  "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY4NTM5NjY2LCJpYXQiOjE3Njc5MzQ4NjYsImp0aSI6IjdkNGJkZDljZjMyMzQyY2VhYzc0ZDU2MTRkNjQyNDNiIiwidXNlcl9pZCI6ImJlZTYxZmMxLTI5ZjQtNGMzOC04ZTZmLTI4YTdiZDE3NTBkMiIsImdyb3VwIjoidXNlciIsInJvbGUiOiJCVVlFUiJ9.UWnUuxRos77nGzXJZAFW6kBH_fzRWtbU5HwQKkjIHMw"
}
"""
